[package]
name = "zero2prod"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
path= "src/main.rs"
name = "zero2prod"

[dependencies]
axum = {version = "0.8.4", features= ["tokio"]}
tokio = {version = "1.45.1", features = ["rt-multi-thread"]}

[dev-dependencies]
reqwest = "0.12.20"
